/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfacturacion.Interfaz;

import java.util.logging.Level;
import java.util.logging.Logger;
import sisfacturacion.Clases.Articulo;

/**
 *
 * @author andre
 */
public class NuevoArticulo extends javax.swing.JFrame {

    /**
     * Creates new form NuevoArticulo
     */
    public NuevoArticulo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estado = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        existencia = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        precioTxt = new javax.swing.JTextField();
        CategoriaTxt = new javax.swing.JTextField();
        ExistenciaTxt = new javax.swing.JTextField();
        AceptarBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setText("NUEVO ARTICULO");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 11, -1, -1));

        codigo.setText("* Codigo:");
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 49, -1, -1));

        nombre.setText("* Nombre:");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 77, -1, -1));

        categoria.setText("Categoria:");
        getContentPane().add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 108, -1, -1));

        precio.setText("* Precio:");
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 139, -1, -1));

        existencia.setText("Existencia:");
        getContentPane().add(existencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 170, -1, -1));

        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 43, 176, -1));

        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 74, 176, -1));

        precioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTxtActionPerformed(evt);
            }
        });
        getContentPane().add(precioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 136, 176, -1));

        CategoriaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(CategoriaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 105, 176, -1));

        ExistenciaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistenciaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(ExistenciaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 167, 176, -1));

        AceptarBt.setText("Aceptar");
        AceptarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 89, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTxtActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void precioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTxtActionPerformed

    private void CategoriaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaTxtActionPerformed

    private void ExistenciaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistenciaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExistenciaTxtActionPerformed

    private void AceptarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtActionPerformed

        try {
            // TODO add your handling code here:
            Articulo art = new Articulo(codigoTxt.getText(),NombreTxt.getText(),Double.parseDouble(precioTxt.getText()));
            art.setCategoria(CategoriaTxt.getText());
            art.setExistencia(Double.parseDouble(ExistenciaTxt.getText()));
            
        } catch (Exception ex) {
            Logger.getLogger(NuevoArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
            
            
        
        
    }//GEN-LAST:event_AceptarBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBt;
    private javax.swing.JTextField CategoriaTxt;
    private javax.swing.ButtonGroup Estado;
    private javax.swing.JTextField ExistenciaTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JLabel existencia;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel precio;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
