
package sisfacturacion.Interfaz;

import java.util.logging.Level;
import java.util.logging.Logger;
import sisfacturacion.Clases.Usuario;


public class NuevoUsuario extends javax.swing.JFrame {


    public NuevoUsuario() {
        initComponents();
        Genero.add(MujerRbt);
        Genero.add(HombreRbt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        Tipo = new javax.swing.ButtonGroup();
        edadTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        HombreRbt = new javax.swing.JRadioButton();
        MujerRbt = new javax.swing.JRadioButton();
        AceptarBt = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        Telefonotxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadTxtActionPerformed(evt);
            }
        });
        getContentPane().add(edadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 157, 176, -1));

        apellidoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        direccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTxtActionPerformed(evt);
            }
        });
        getContentPane().add(direccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 186, 176, -1));

        HombreRbt.setText("Hombre");
        HombreRbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HombreRbtActionPerformed(evt);
            }
        });
        getContentPane().add(HombreRbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 132, -1, -1));

        MujerRbt.setText("Mujer");
        MujerRbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MujerRbtActionPerformed(evt);
            }
        });
        getContentPane().add(MujerRbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 132, -1, -1));

        AceptarBt.setText("Aceptar");
        AceptarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 88, 38));

        titulo.setText("NUEVO USUARIO");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 11, -1, -1));

        codigo.setText("* Codigo:");
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 49, -1, -1));

        nombre.setText("* Nombre:");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 77, -1, -1));

        apellido.setText("*Apellido:");
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 108, -1, -1));

        edad.setText("Edad:");
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 160, -1, -1));

        direccion.setText("Direccion:");
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 192, -1, -1));

        genero.setText("Genero:");
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 136, -1, -1));

        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 43, 176, -1));

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 74, 176, -1));

        telefono.setText("*Telefono:");
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 223, -1, -1));

        Telefonotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonotxtActionPerformed(evt);
            }
        });
        getContentPane().add(Telefonotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 217, 176, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadTxtActionPerformed

    private void apellidoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTxtActionPerformed

    private void direccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTxtActionPerformed

    private void HombreRbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HombreRbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HombreRbtActionPerformed

    private void MujerRbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MujerRbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MujerRbtActionPerformed

    private void AceptarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtActionPerformed

      
        try {   
            Usuario user = new Usuario(codigoTxt.getText(), nombreTxt.getText(), apellidoTxt.getText(), Telefonotxt.getText());
            user.setEdad(Integer.parseInt(edadTxt.getText()));
            user.setDireccion(direccionTxt.getText());
            if(HombreRbt.isSelected() == true){
                user.setGenero("Hombre");
            }else{
                user.setGenero("Mujer");
            }
        } catch (Exception ex) {
            Logger.getLogger(NuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_AceptarBtActionPerformed

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTxtActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void TelefonotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonotxtActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBt;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JRadioButton HombreRbt;
    private javax.swing.JRadioButton MujerRbt;
    private javax.swing.JTextField Telefonotxt;
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JLabel apellido;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JLabel edad;
    private javax.swing.JTextField edadTxt;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
