/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfacturacion.Interfaz;

import java.util.logging.Level;
import java.util.logging.Logger;
import sisfacturacion.Clases.Servicio;

/**
 *
 * @author andre
 */
public class NuevoServicio extends javax.swing.JFrame {

    /**
     * Creates new form NuevoServicio
     */
    public NuevoServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precioTxt = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        AceptarBt = new javax.swing.JButton();
        precio = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTxtActionPerformed(evt);
            }
        });
        getContentPane().add(precioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 105, 176, -1));

        title.setText("NUEVO SERVICIO");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 11, -1, -1));

        codigo.setText("* Codigo:");
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 49, -1, -1));

        nombre.setText("* Nombre:");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 77, -1, -1));

        AceptarBt.setText("Aceptar");
        AceptarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 36));

        precio.setText("* Precio:");
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 108, -1, -1));

        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 43, 176, -1));

        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 74, 176, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTxtActionPerformed

    private void AceptarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtActionPerformed

       
        try {
            // TODO add your handling code here:
            Servicio service = new Servicio(codigoTxt.getText(),NombreTxt.getText(),Double.parseDouble(precioTxt.getText()));
        } catch (Exception ex) {
            Logger.getLogger(NuevoServicio.class.getName()).log(Level.SEVERE, null, ex);
        }
      

    }//GEN-LAST:event_AceptarBtActionPerformed

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTxtActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel precio;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
