/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfacturacion.Interfaz;

import java.util.logging.Level;
import java.util.logging.Logger;
import sisfacturacion.Clases.Usuario;

/**
 *
 * @author andre
 */
public class NuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsuario
     */
    public NuevoUsuario() {
        initComponents();
        Genero.add(MujerRbt);
        Genero.add(HombreRbt);
        
        Tipo.add(AdminRbt);
        Tipo.add(UserRbt);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        Tipo = new javax.swing.ButtonGroup();
        edadTxt = new javax.swing.JTextField();
        apellidotxt = new javax.swing.JTextField();
        DireccionTxt = new javax.swing.JTextField();
        HombreRbt = new javax.swing.JRadioButton();
        MujerRbt = new javax.swing.JRadioButton();
        AceptarBt = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        genero = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        Telefonotxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        UserRbt = new javax.swing.JRadioButton();
        AdminRbt = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadTxtActionPerformed(evt);
            }
        });
        getContentPane().add(edadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 157, 176, -1));

        apellidotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidotxtActionPerformed(evt);
            }
        });
        getContentPane().add(apellidotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        DireccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionTxtActionPerformed(evt);
            }
        });
        getContentPane().add(DireccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 186, 176, -1));

        HombreRbt.setText("Hombre");
        HombreRbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HombreRbtActionPerformed(evt);
            }
        });
        getContentPane().add(HombreRbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 132, -1, -1));

        MujerRbt.setText("Mujer");
        MujerRbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MujerRbtActionPerformed(evt);
            }
        });
        getContentPane().add(MujerRbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 132, -1, -1));

        AceptarBt.setText("Aceptar");
        AceptarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBtActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 88, 38));

        title.setText("NUEVO USUARIO");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 11, -1, -1));

        codigo.setText("* Codigo:");
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 49, -1, -1));

        nombre.setText("* Nombre:");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 77, -1, -1));

        apellido.setText("*Apellido:");
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 108, -1, -1));

        edad.setText("Edad:");
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 160, -1, -1));

        direccion.setText("Direccion:");
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 192, -1, -1));

        genero.setText("Genero:");
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 136, -1, -1));

        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });
        getContentPane().add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 43, 176, -1));

        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 74, 176, -1));

        telefono.setText("*Telefono:");
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 223, -1, -1));

        Telefonotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonotxtActionPerformed(evt);
            }
        });
        getContentPane().add(Telefonotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 217, 176, -1));

        jLabel1.setText("Tipo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        UserRbt.setText("Usuario");
        UserRbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRbtActionPerformed(evt);
            }
        });
        getContentPane().add(UserRbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        AdminRbt.setText("Administrador");
        getContentPane().add(AdminRbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadTxtActionPerformed

    private void apellidotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidotxtActionPerformed

    private void DireccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionTxtActionPerformed

    private void HombreRbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HombreRbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HombreRbtActionPerformed

    private void MujerRbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MujerRbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MujerRbtActionPerformed

    private void AceptarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBtActionPerformed

      
        try {   
            Usuario user = new Usuario(codigoTxt.getText(), NombreTxt.getText(), apellidotxt.getText(), Telefonotxt.getText(),UserRbt.isSelected());
            user.setEdad(Integer.parseInt(edadTxt.getText()));
            user.setDireccion(DireccionTxt.getText());
            if(HombreRbt.isSelected() == true){
                user.setGenero("Hombre");
            }else{
                user.setGenero("Mujer");
            }
        } catch (Exception ex) {
            Logger.getLogger(NuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_AceptarBtActionPerformed

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTxtActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void TelefonotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonotxtActionPerformed

    private void UserRbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserRbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBt;
    private javax.swing.JRadioButton AdminRbt;
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JRadioButton HombreRbt;
    private javax.swing.JRadioButton MujerRbt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField Telefonotxt;
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JRadioButton UserRbt;
    private javax.swing.JLabel apellido;
    private javax.swing.JTextField apellidotxt;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel edad;
    private javax.swing.JTextField edadTxt;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
